[phases.setup]
commands = [
  "cargo install sqlx-cli --no-default-features --features mysql", # Install the sqlx CLI with MySQL support
  "sqlx migrate run"  # Run the migrations after installing the CLI
]

[phases.build]
commands = [
  "cargo build --release"
]
